"""Scrape https://arxiv.org/category_taxonomy -> registry/arxiv_categories.yaml.

Same convention as `build_registry.py`: the taxonomy is *generated from the source
of truth*, not hand-typed, so it can be refreshed when arXiv adds a category and a
diff shows exactly what changed. Raw HTML is cached under `registry/cache/`.

The page gives the 8 top-level groups and every current subject class
(`cs.LG (Machine Learning)`). It does NOT list the pre-2007 archives that were
renamed (`cmp-lg` -> `cs.CL`, `alg-geom` -> `math.AG`, ...); those are hard-coded in
LEGACY_ARCHIVES below with the rename each one underwent, because roughly a third of
arXiv predates the current scheme and those papers must land in the same `field` as
their modern equivalents.

  python -m accelscan.scripts.build_arxiv_taxonomy            # refresh from cache
  python -m accelscan.scripts.build_arxiv_taxonomy --no-cache # refetch
"""

import argparse
import sys
import urllib.request
from pathlib import Path

TAXONOMY_URL = 'https://arxiv.org/category_taxonomy'
CACHE = Path('registry/cache/arxiv_category_taxonomy.html')
OUT = Path('registry/arxiv_categories.yaml')
UA = 'accelscan/0.1 (metascience research; contact gebhart@umn.edu)'

# Pre-2007 archives, with the modern archive each was folded into. Not on the
# taxonomy page: arXiv documents these renames in its identifier history.
LEGACY_ARCHIVES = {
    'acc-phys': ('physics', 'physics.acc-ph'),
    'adap-org': ('nlin', 'nlin.AO'),
    'alg-geom': ('math', 'math.AG'),
    'ao-sci': ('physics', 'physics.ao-ph'),
    'atom-ph': ('physics', 'physics.atom-ph'),
    'bayes-an': ('physics', 'physics.data-an'),
    'chao-dyn': ('nlin', 'nlin.CD'),
    'chem-ph': ('physics', 'physics.chem-ph'),
    'cmp-lg': ('cs', 'cs.CL'),
    'comp-gas': ('nlin', 'nlin.CG'),
    'dg-ga': ('math', 'math.DG'),
    'funct-an': ('math', 'math.FA'),
    'mtrl-th': ('cond-mat', 'cond-mat.mtrl-sci'),
    'patt-sol': ('nlin', 'nlin.PS'),
    'plasm-ph': ('physics', 'physics.plasm-ph'),
    'q-alg': ('math', 'math.QA'),
    'solv-int': ('nlin', 'nlin.SI'),
    'supr-con': ('cond-mat', 'cond-mat.supr-con'),
}


def fetch(use_cache: bool = True) -> str:
    if use_cache and CACHE.exists():
        return CACHE.read_text()
    req = urllib.request.Request(TAXONOMY_URL, headers={'User-Agent': UA})
    html = urllib.request.urlopen(req, timeout=60).read().decode('utf-8', errors='replace')
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    CACHE.write_text(html)
    return html


def parse(html: str) -> tuple[dict[str, list[str]], dict[str, str]]:
    """-> ({group: [archives]}, {subject_class: display name}).

    Walks h2/h4 in document order: h2 opens a group, h4 carries
    'cs.LG (Machine Learning)'. The archive is the code's prefix, so Physics'
    per-archive h3 headings need no special handling.
    """
    from bs4 import BeautifulSoup
    root = BeautifulSoup(html, 'html.parser').find(id='category_taxonomy_list')
    if root is None:
        raise RuntimeError('category_taxonomy_list not found; page structure changed')

    groups: dict[str, list[str]] = {}
    names: dict[str, str] = {}
    group = None
    for el in root.find_all(['h2', 'h4']):
        text = ' '.join(el.get_text(' ', strip=True).split())
        if el.name == 'h2':
            group = None if text.lower().startswith(('classification', 'group name')) \
                else text
            if group:
                groups.setdefault(group, [])
            continue
        if group is None or '(' not in text:
            continue
        code = text.split()[0]
        display = text[text.index('(') + 1:text.rindex(')')].strip()
        names[code] = display
        archive = code.split('.')[0]
        if archive not in groups[group]:
            groups[group].append(archive)
    return groups, names


def render(groups: dict[str, list[str]], names: dict[str, str]) -> str:
    lines = [
        '# arXiv category taxonomy -> field labels for the arXiv corpus.',
        '#',
        '# GENERATED by `python -m accelscan.scripts.build_arxiv_taxonomy` from',
        f'# {TAXONOMY_URL} -- do not hand-edit; rerun the scraper so a diff shows',
        '# exactly what arXiv changed. Legacy renames live in that script.',
        '#',
        '# The arXiv corpus uses arXiv\'s own taxonomy, not `s2fieldsofstudy`: the two',
        '# corpora are reported separately, and arXiv classifies its own papers better',
        '# than a classifier guesses. `field` is the group; `primary_category` (cs.LG,',
        '# astro-ph.GA) is carried alongside for the fine-grained breakdowns that have',
        '# no S2ORC analogue. `categories` supplies human-readable labels for figures.',
        '#',
        '# `tests/test_arxiv_meta.py` fails if any archive -- current or legacy -- is',
        '# unmapped: an unmapped archive yields a null `field`, which would silently',
        '# drop those papers out of every field figure instead of failing.',
        'version: "2.0"',
        f'source: {TAXONOMY_URL}',
        '',
        '# group -> the archives it contains (an archive is the part before the dot)',
        'groups:',
    ]
    for group in sorted(groups):
        lines.append(f'  {group}:')
        lines += [f'    - {a}' for a in sorted(groups[group])]
    lines += ['', '# pre-2007 archive -> the modern archive that absorbed it',
              'legacy:']
    for old, (archive, became) in sorted(LEGACY_ARCHIVES.items()):
        lines.append(f'  {old}: {archive}'.ljust(28) + f'# -> {became}')
    lines += ['', '# subject class -> display name (for figure labels)', 'categories:']
    for code in sorted(names):
        display = names[code].replace('"', "'")
        lines.append(f'  {code}: "{display}"')
    return '\n'.join(lines) + '\n'


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--no-cache', action='store_true')
    ap.add_argument('--out', default=str(OUT))
    args = ap.parse_args()

    groups, names = parse(fetch(use_cache=not args.no_cache))
    archives = {a for v in groups.values() for a in v}
    print(f'{len(groups)} groups, {len(archives)} current archives, '
          f'{len(names)} subject classes, {len(LEGACY_ARCHIVES)} legacy archives',
          file=sys.stderr)
    for g in sorted(groups):
        print(f'  {g}: {len(groups[g])} archives', file=sys.stderr)

    stale = set(LEGACY_ARCHIVES) & archives
    if stale:
        print(f'WARNING: legacy archives that are also current: {sorted(stale)}',
              file=sys.stderr)
    unresolved = {o: a for o, (a, _) in LEGACY_ARCHIVES.items() if a not in archives}
    if unresolved:
        raise SystemExit(f'legacy targets not in the current taxonomy: {unresolved}')

    Path(args.out).write_text(render(groups, names))
    print(f'wrote {args.out}', file=sys.stderr)


if __name__ == '__main__':
    main()
