"""Derive notebooks/arxiv/*.ipynb from the S2ORC originals.

Generated, not hand-copied, for the same reason the registry is: hand-duplicating six
notebooks is how the missing `plt.show()` and the 100x-wrong percent formatter got in.
Rerun this after editing an S2ORC notebook and the arXiv twin follows instead of
drifting. **Every rule asserts that it matched**, so a rule that silently stops
applying because a cell was reworded is a hard error rather than a no-op.

  python -m accelscan.scripts.make_arxiv_notebooks
  python -m accelscan.scripts.make_arxiv_notebooks --only capacity

What changes, and why:

- `setup_figures('arxiv/<nb>')` -> figures land in output/analysis/arxiv/<nb>/ instead
  of overwriting the S2ORC ones.
- `YEAR_MIN, YEAR_MAX = 2005, 2026`. arXiv only: a paper is in the source tars the
  month it is submitted, so 2026 is real data, whereas S2ORC's 2026 holds 8% of a
  year's papers and would be pure ingestion artefact. 2026 is still partial, so mark
  it on count-based figures.
- `'corpusid'` -> `KEY` everywhere in code. arXiv's key is `paper_id`
  (`arxiv:2301.01234`) and its `corpusid` column is null by design.
- S3 paths go through `accelscan.paths` builders instead of f-strings over
  `OUT_PREFIX`, which is what puts them under `accelscan/arxiv/`.
- Field/year enrichment goes through `meta.paper_fields`, because arXiv has no
  `s2fieldsofstudy` -- `field` comes from arXiv's own taxonomy and is already a
  column, and `primary_category` has no S2ORC analogue.
- `productivity` loses §6.4 and the citation half of rank-stability: there is no
  arXiv->S2 crosswalk, so no forward citations. Half-life and adoption lag survive,
  since they need only year and model.
- A caveat cell is prepended to every notebook: preprint self-selection,
  physics/CS skew, and raw-LaTeX matching that reads captions and comments -- so
  arXiv levels are biased upward relative to S2ORC and only within-corpus trends are
  comparable.
"""

import argparse
import copy
import json
import sys
from pathlib import Path

SRC = Path('notebooks')
DST = Path('notebooks/arxiv')
NOTEBOOKS = ('trends', 'capacity', 'productivity', 'manufacturer', 'gpu_usage')

IMPORTS = """from accelscan.meta import paper_fields
from accelscan.paths import (analytic_base, candidates_root, capacity_key,
                             get_corpus, precision_key, s3_uri)
"""

KNOBS = """
CORPUS = 'arxiv'
c = get_corpus(CORPUS); KEY = c.key      # 'paper_id'; corpusid is null for arXiv

# arXiv's group names are too long for legends and axis ticks. Applied at every point
# `field` enters, so the short form is what every figure and table shows.
FIELD_LABELS = {'Electrical Engineering and Systems Science': 'EE and Systems',
                'Quantitative Biology': 'Quant. Biology',
                'Quantitative Finance': 'Quant. Finance'}
short_fields = lambda df: df.with_columns(pl.col('field').replace(FIELD_LABELS))
"""

CAVEAT = """## arXiv corpus — read this first

This is the **arXiv** twin of the S2ORC notebook, generated by
`accelscan.scripts.make_arxiv_notebooks`. Edit the S2ORC original and regenerate.

Four things make arXiv levels **not** comparable to S2ORC levels:

1. **Self-selected preprints**, skewed to physics and CS, with no peer-review filter.
2. **Raw-LaTeX matching.** The matcher reads the `.tex` source, which includes figure
   captions, spec tables, code listings and `%` comments that GROBID drops from
   S2ORC. This biases any-mention prevalence *upward*; `reported use` and
   model-specific series are better protected because the LLM judges the passage.
3. **No citations.** There is no arXiv→corpusid crosswalk, so §6.4-style citation
   analyses are absent here.
4. **1991–2026 available, 2005–2026 analysed.** 2026 is a partial calendar year:
   fine for shares, marked on counts.

Only **within-corpus trends** should be compared across the two corpora.
"""

# (notebook, old, new). Applied to code cells; each must match exactly once overall.
RULES = {
    None: [                                    # every notebook
        # No cwd guard at all: the kernel starts at the repo root, so chdir'ing only
        # breaks relative paths that were already correct.
        ("""import os
if os.path.basename(os.getcwd()) == 'notebooks':
    os.chdir('..')
""", "", 'optional'),
        # PAPERS_PREFIX is the S2 metadata table; arXiv gets field/year from
        # meta.paper_fields instead, so the import goes with it
        ("from accelscan.config import BUCKET, OUT_PREFIX, PAPERS_PREFIX",
         "from accelscan.config import BUCKET, OUT_PREFIX", 'optional'),
        # anchored on the import line's end, since notebooks import different names
        # from accelscan.plotting (productivity also takes spread_labels)
        ("from accelscan.plotting import ", "%%PLOTTING%%"),
        ("YEAR_MIN, YEAR_MAX = 2005, 2025", "YEAR_MIN, YEAR_MAX = 2005, 2026"),
        # figure titles name the corpus, and the title is also the exported filename
        ("title='S2ORC full-text corpus size'", "title='arXiv corpus size'", 'optional'),
        # trends/productivity/manufacturer take field from the denominator table;
        # capacity and gpu_usage take it from paper_fields (shortened in their own rules)
        ("den = rd('denominator')", "den = short_fields(rd('denominator'))", 'optional'),
        # capacity splits these onto two lines; match the last one either way
        ("so = storage_options()", "so = storage_options()" + KNOBS),
        # mentions_glob defaults to the S2ORC prefix, so an un-rewritten call reads
        # the wrong corpus' table and only fails later, on the missing paper_id column
        ("mentions_glob(MODEL_TAG, PROMPT_VERSION)",
         "mentions_glob(MODEL_TAG, PROMPT_VERSION, corpus=c)", 'optional'),
        # stored candidate passages are read by the CUDA lock-in proxy (manufacturer)
        # and the tier-B rescue share (trends); for arXiv they live under
        # accelscan/arxiv/candidates/. candidates_root already ends in '/' --
        # re-adding one lists nothing at all.
        ("prefix = f'{OUT_PREFIX}/candidates/'", "prefix = candidates_root(c)",
         'optional'),
        # OPTIONAL: a notebook-specific rule above may already have consumed this
        ("""f's3://{BUCKET}/{OUT_PREFIX}/analytic/{reg.version}/{PROMPT_VERSION}/{MODEL_TAG}'""",
         "s3_uri(analytic_base(c, reg.version, PROMPT_VERSION, MODEL_TAG))", 'optional'),
    ],
    'capacity': [
        ("""    key = (f's3://{BUCKET}/{OUT_PREFIX}/capacity/{reg.version}/{PROMPT_VERSION}'
           f'/{MODEL_TAG}/paper_capacity_{COUNT_POLICY}.parquet')""",
         "    key = s3_uri(capacity_key(c, reg.version, PROMPT_VERSION, MODEL_TAG,\n"
         "                             COUNT_POLICY))"),
        ("""flag_ids = pl.read_parquet(
    f's3://{BUCKET}/{OUT_PREFIX}/analytic/{reg.version}/{PROMPT_VERSION}/{MODEL_TAG}'
    f'/paper_flags.parquet', storage_options=so, columns=['corpusid'])""",
         "flag_ids = pl.read_parquet(\n"
         "    f'{s3_uri(analytic_base(c, reg.version, PROMPT_VERSION, MODEL_TAG))}"
         "/paper_flags.parquet',\n"
         "    storage_options=so, columns=[KEY])"),
        # arXiv has no s2fieldsofstudy: field comes from its own taxonomy via meta
        ("""fields = (pl.scan_parquet(f's3://{BUCKET}/{PAPERS_PREFIX}*.parquet', storage_options=so)
          .select('corpusid', 's2fieldsofstudy')
          .filter(pl.col('corpusid').is_in(need))
          .with_columns(field=pl.col('s2fieldsofstudy').list.first().struct.field('category'))
          .select('corpusid', 'field').collect())""",
         "fields = short_fields(paper_fields(c, pl.DataFrame({KEY: need}), so))\\\n"
         "         .select(KEY, 'field')"),
        ("""            f's3://{BUCKET}/{OUT_PREFIX}/precision/0.1.0/paper_precision.parquet',""",
         "            s3_uri(precision_key(c, '0.1.0')),"),
    ],
    'gpu_usage': [
        ("""    return (f's3://{BUCKET}/{OUT_PREFIX}/mentions/{reg.version}'
            f'/{PROMPT_VERSION}/{MODEL_TAG}/parts/*.parquet')""",
         "    from accelscan.s3 import mentions_glob as _mg\n"
         "    return _mg(MODEL_TAG, PROMPT_VERSION, corpus=c)"),
        ("""    papers = (pl.scan_parquet(f's3://{BUCKET}/{PAPERS_PREFIX}*.parquet', storage_options=so)
              .select('corpusid', 'year', 's2fieldsofstudy')
              .filter(pl.col('corpusid').is_in(ids))
              .with_columns(field=pl.col('s2fieldsofstudy').list.first().struct.field('category'))
              .select('corpusid', 'year', 'field')
              .collect())""",
         "    papers = short_fields(paper_fields(c, pl.DataFrame({KEY: ids}), so))\\\n"
         "        .select(KEY, 'year', 'field')"),
    ],
    'productivity': [
        ("den = rd('denominator').select('corpusid', 'year', 'field')\ncit = rd('citations')",
         "den = rd('denominator').select(KEY, 'year', 'field')\n"
         "# no citations for arXiv: there is no arXiv->corpusid crosswalk"),
        ("""      .join(meta, on='canonical_model', how='left')
      .join(cit.select('corpusid', citations=f'i_{CITE_WINDOW}',
                       has_outcomes='has_outcomes'), on='corpusid', how='left'))""",
         "      .join(meta, on='canonical_model', how='left'))"),
        ("""# i_k is populated even where k years have not elapsed, so completeness has to come
# from the publication year, not from null-ness: i_3 is complete for papers <= 2022
# under the same outcomes build that made i_5 complete only through 2020.
pm = pm.with_columns(cite_window_complete=pl.col('year') <= CITE_CUTOFF)
""", ""),
        ("CITE_WINDOW = 3             # years of forward citations (i_3); "
         "i_1/i_5/i_10 also available\n"
         "CITE_CUTOFF = 2023          # last year with a complete CITE_WINDOW in the "
         "outcomes build\n", ""),
    ],
}

# Prose rules, applied to markdown cells only. Same match-or-fail contract as RULES:
# a figure title or a validity note that still says "S2ORC" is a wrong claim about
# this corpus, not a cosmetic slip.
MD_RULES = {
    None: [
        ('the S2ORC full-text', 'the arXiv full-text', 'optional'),
    ],
    'productivity': [
        # the audited numbers and their causes are S2ORC's; arXiv dates come from the
        # id (= v1 submission), so the metadata-error cause does not carry over
        ("""Audited on the full run: **~0.08% of used-model observations are pre-release**
(102 at -1 year, 21 at -2, 11 at -3 or earlier). Identified causes: S2ORC year
metadata errors (one paper dated **1970** — a Unix-epoch default), preprint /
version date mismatches, and a handful of registry release dates that are a
year off.""",
         """The rate for this corpus is computed below. arXiv years are derived from the
id, i.e. the v1 submission month, so the S2ORC metadata errors behind its
~0.08% do not apply here; what remains is a genuine preprint effect (a paper
posted before a chip ships, then revised) plus registry release dates that are
a year off."""),
    ],
}

# Cells removed wholesale: the citation section and the citation half of rank-stability.
DROP_CELLS = {'productivity': (18, 19, 20, 21)}


def transform(nb: str) -> dict:
    d = json.loads((SRC / f'{nb}.ipynb').read_text())
    for i in sorted(DROP_CELLS.get(nb, ()), reverse=True):
        del d['cells'][i]

    # notebook-specific rules first: several contain the generic analytic
    # f-string, and letting the generic rule fire first would stop them matching
    rules = list(RULES.get(nb, [])) + list(RULES[None])
    rules.append((f"setup_figures('{nb}')", f"setup_figures('arxiv/{nb}')"))
    md_rules = list(MD_RULES.get(nb, [])) + list(MD_RULES[None])
    counts = {r[0]: 0 for r in rules + md_rules}
    optional = {r[0] for r in rules + md_rules if len(r) > 2}
    for cell in d['cells']:
        if cell['cell_type'] != 'code':
            md = ''.join(cell['source'])
            for old, new, *_ in md_rules:
                if old in md:
                    counts[old] += md.count(old)
                    md = md.replace(old, new)
            md = md.replace('`s2fieldsofstudy`', "arXiv's own taxonomy")
            cell['source'] = md.replace('s2fieldsofstudy',
                                        'arXiv category').splitlines(keepends=True)
            continue
        src = ''.join(cell['source'])
        for old, new, *_ in rules:
            if old in src:
                counts[old] += src.count(old)
                src = src.replace(old, new)
        if '%%PLOTTING%%' in src:
            head, rest = src.split('%%PLOTTING%%', 1)
            names, tail = rest.split('\n', 1)
            src = (f'{head}from accelscan.plotting import {names}\n'
                   f'{IMPORTS}{tail}')
        src = src.replace("'corpusid'", 'KEY').replace('"corpusid"', 'KEY')
        # prose/comments: the taxonomy is arXiv's, not S2's. Runs after the rules
        # above, whose patterns still contain the literal column name.
        src = src.replace('`s2fieldsofstudy`', "arXiv's own taxonomy")
        src = src.replace('s2fieldsofstudy', 'arXiv category')
        cell['source'] = src.splitlines(keepends=True)
        cell['outputs'], cell['execution_count'] = [], None

    unmatched = [o for o, n in counts.items() if n == 0 and o not in optional]
    if unmatched:
        raise SystemExit(f'{nb}: {len(unmatched)} rule(s) matched nothing -- the source '
                         f'notebook changed:\n  ' + '\n  '.join(repr(u[:70])
                                                               for u in unmatched))
    # Outcome check, stronger than per-rule matching: no S2ORC-only reference may
    # survive. A path left over on OUT_PREFIX would silently read the S2ORC table.
    for i, cell in enumerate(d['cells']):
        if cell['cell_type'] != 'code':
            continue
        body = ''.join(cell['source'])
        for bad in ('{OUT_PREFIX}', 'PAPERS_PREFIX', "'corpusid'", '"corpusid"',
                    's2fieldsofstudy',
                    'mentions_glob(MODEL_TAG, PROMPT_VERSION)'):
            if bad in body:
                raise SystemExit(f'{nb}: cell {i} still references {bad!r} after '
                                 f'transformation')
    d['cells'].insert(0, {'cell_type': 'markdown', 'metadata': {},
                          'source': CAVEAT.splitlines(keepends=True)})
    return d


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--only', nargs='*', default=NOTEBOOKS)
    args = ap.parse_args()
    DST.mkdir(parents=True, exist_ok=True)
    for nb in args.only:
        d = transform(nb)
        out = DST / f'{nb}.ipynb'
        out.write_text(json.dumps(d, indent=1) + '\n')
        print(f'wrote {out} ({len(d["cells"])} cells)', file=sys.stderr)


if __name__ == '__main__':
    main()
